### PR TITLE
The player can become a guard after passing the fire mage trial

### PR DESCRIPTION
**Pull request by AmProsius**
**Describe the bug**
After passing the trial, the player can go to Thorus to become a guard and then complete the ceremony to become a fire mage.

**Expected behavior**
It is no longer possible to become a guard after passing the trial of the Magicians of Fire.

### CODE REVIEW

**Review by szapp — APPROVED** [review]
I have not run the test, but it looks good.

**Comment by Quintus24** [comment]
Hello, everyone,

Sorry for spamming a closed report, however, I can still reproduce this issue.

After I pass the **Fire Mage** trial, **Corristo** goes to prepare the oath ceremony.
In the meantime, I can go back to **Thorus** and tell him I want to be a guard, he accepts and I can go and get armor from **Stone**.
Afterwards, I can go back to **Corristo** to begin the oath ceremony and become a **Fire Mage**.

Regards,
Quintus24

**Comment by szapp** [comment]
@Quintus24 thanks for reporting! Would you mind to give a detailed account on which dialogs where spoken in which order? There are a few dialogs in play (Thorus and Corristo) that may happen in different order. It would be useful how you managed to spli through. According to the scripts that should be not possible. What can happen, however, I noticed is that **before** Corristo’s questioning is concluded, one can go back to Thorus to become a guard and then continue Corristo’s quiz to become a mage afterward. I haven’t tried it in-game. If that is the case it should be addressed, too.

**Comment by Quintus24** [comment]
Hi @szapp, 

Here are the exact steps:
1. Speak with **Thorus** and select the "**_You have something to tell me?_**" option.
2. Wait for **Throus** to finish his reply and select the "**_I'm interested in the path of magic._**" option.
3. Go to **Milten**, he will instruct you to talk with **Corristo**. (Milten, in my case, will trigger the dialog when approached, I forgot to deliver the **Letter** in my playthrough).
4. Talk with **Corristo** and select the "**_I'd like to enter the magic Circle._**" option.
5. Wait for **Corristo** to finish his speech and select "**_I'm up for it. Just test me._**"
6. Begin the trial and answer the first question by selecting "**_Yes_**".
7. Answer the second question by selecting "**Innos**".
8. Answer the third question by selecting "**_Humility in the face of magic_**".
9. **Corristo** will acknowledge your answers and invites you to the ritual.
10. Head back to **Thorus** and select the "**I want to become a guard.**" option.
11. Listen to **Thorus** speech and wait for him to finish and to welcome you into the **Guards**.
11.5. (optional: go to **Stone** and get your **sword** and **armor**)
12. Go back to **Corristo** and begin the ritual.
13. Wait for the ceremony to end and become a **Fire Mage**.

I have attached my save file, maybe it will help.
[savegame1.zip](https://github.com/AmProsius/gothic-1-community-patch/files/8647357/savegame1.zip)

> What can happen, however, I noticed is that **before** Corristo’s questioning is concluded, one can go back to Thorus to become a guard and then continue Corristo’s quiz to become a mage afterward. I haven’t tried it in-game. If that is the case it should be addressed, too.

I can reproduce this as well, however, once the quiz begins, you cannot back out, it is mandatory to finish it.
Therefore, you can ask **Corristo** to join, don't start the quiz, go back to **Thorus** and join the **Guards**, then return to **Corristo** to begin the quiz and become **Fire Mage**.

While doing these tests I also noticed that **Corristo's** daily routine will no longer resume if the following steps are performed:
1. Speak with **Thorus** and select the "**_You have something to tell me?_**" option.
2. Wait for **Throus** to finish his reply and select the "**_I'm interested in the path of magic._**" option.
3. Go and check if **Corristo** is ready to talk with you, (if he is behind **Milten**).
4. Head back to **Thorus** and select the "**I want to become a guard.**" option.
5. Become a **Guard** and notice that **Corristo** will remain in his position, behind **Milten**, indefinitely.
6. Talk with **Corristo** and notice the "**END**" string in the dialogue box.

Regards,
Quintus24

**Pull request merged**
