### PR TITLE
Guard has duplicated END dialog

### PR DESCRIPTION
**Pull request by AmProsius**
**Describe the bug**
The guard right next to Glen in the old mine has two ending dialogue options. 

**Expected behavior**
There should be just one option to end the dialogue.

**Additional context**
Instance `Grd_264_Gardist`.

### CODE REVIEW

**Review by szapp — CHANGES_REQUESTED** [review]
I think it's quite elegant to piggyback #42!

However, the fix status of #42 will mark as failed if the two dialogs in #42 are in fact fixed but the one from #128 is not. Same for the opposite. That is highly misleading and could cause a lot of headaches during testing.

I propose to rather copy and adjust the function `G1CP_042_GuardExitDialog` while re-using the function `G1CP_042_ConfirmByteCode` (no need to copy that one).

**Comment by AmProsius** [comment]
Wouldn't it be even better then to split #42 in two separate fixes?

**Comment by szapp** [comment]
> Wouldn't it be even better then to split the original #42 in two separate fixes as well?

Yes, I agree. This would allow for best inspection during testing. But I fear that it would convolute the fix list / changelog, with many identical entries. An alternative is to collect all of them in one fix, as done in #42 so far.

Both options have their pros and cons, I will leave this decision up to you.

**Comment by szapp** [comment]
Thanks for taking care of it. There are a few things that may not work with the new changes. I don't have the time to get into it right now, but hold out before merging this PR.

**Review by szapp — CHANGES_REQUESTED** [review]

**Review by szapp — APPROVED** [review]

**Pull request merged**
