### PR TITLE
Gravo not listed as merchant 

### PR DESCRIPTION
**Pull request by szapp**
Gravo isn't listed in "Diary/General info/Merchant in the Old Camp" if the topic wasn't previously created.

### CODE REVIEW

**Comment by szapp** [comment]
The test is still missing.

**Comment by AmProsius** [comment]
Just to save it somewhere (Regex: `\s+\n\s*B_LogEntry\s*\(\s?GE`), these are the log entries that might not be created due to lacking `Log_CreateTopic`:

```
C:\Users\amprosius\projects\gothic-1-community-patch\scriptbase\_work\Data\Scripts\Content\Story\Missions\DIA_GRD_219_Stone.d:
  104      CreateInvItem       (other,GRD_ARMOR_L);
  105      AI_EquipBestArmor   (hero);
  106:     AI_EquipBestMeleeWeapon (hero);
  107: 
  108:     B_LogEntry      (GE_BecomeGuard,"I've collected my first guard's armor at the smith Stone's. I could even buy better armor there, but he's prices are high.");
  109  
  110      AI_StopProcessInfos ( self );

C:\Users\amprosius\projects\gothic-1-community-patch\scriptbase\_work\Data\Scripts\Content\Story\Missions\DIA_KDF_402_Corristo.d:
  335      hero.guild = GIL_KDF;
  336  
  337:     hero.attribute [ATR_HITPOINTS] = hero.attribute [ATR_HITPOINTS_MAX];
  338: 
  339:     B_LogEntry      (GE_BecomeFiremage,"I've passed the test and sworn the oath of Fire. From now on I'll wear the red robe of the Circle of Fire!");
  340      Log_CreateTopic (GE_TeacherOC,LOG_NOTE);
  341      B_LogEntry      (GE_TeacherOC,"Corristo can teach me the magic CIRCLES and increase my MANA. He's in the house of the Magicians of Fire.");

C:\Users\amprosius\projects\gothic-1-community-patch\scriptbase\_work\Data\Scripts\Content\Story\Missions\DIA_ORG_855_Wolf.d:
   46  {
   47      AI_Output           (other, self,"DIA_Wolf_Hello_15_00"); //Who are you?
   48:     AI_Output           (self, other,"DIA_Wolf_Hello_09_01"); //I'm Wolf. I make armor.
   49: 
   50:     B_LogEntry          (GE_TraderNC,"Wolf supplies the rogues with ARMOR. He's usually in front of his hut in the big living cave.");
   51  };
   52  

C:\Users\amprosius\projects\gothic-1-community-patch\scriptbase\_work\Data\Scripts\Content\Story\Missions\DIA_STT_331_Fingers.d:
  222      AI_Output (other, self,"DIA_Fingers_WhereCavalorn_15_00"); //Where can I find Cavalorn?
  223      AI_Output (self, other,"DIA_Fingers_WhereCavalorn_05_01"); //He's hunting out in the wild. You'll find him at the path to the New Camp. Westwards of the Old Camp there's a wide canyon.
  224:     AI_Output (self, other,"DIA_Fingers_WhereCavalorn_05_02"); //In this canyon there's an old woodcutters' hut. You'll find him there.
  225: 
  226:     B_LogEntry( GE_TeacherOW,"Cavalorn can teach me to sneak. His hut is in a canyon to the west of the Old Camp, in the direction of the New Camp.");
  227  };
  228  

C:\Users\amprosius\projects\gothic-1-community-patch\scriptbase\_work\Data\Scripts\Content\Story\Missions\DIA_TPL_1402_GorNaToth.d:
  135      AI_Output           (other, self,"TPL_1402_GorNaToth_GETSTUFF_Info_15_01"); //I'd like to collect my templar's armor.
  136      AI_Output           (self, other,"TPL_1402_GorNaToth_GETSTUFF_Info_11_02"); //I'm delighted to have the honor of handing our armor to the man who found the minecrawler eggs.
  137:     AI_Output           (self, other,"TPL_1402_GorNaToth_GETSTUFF_Info_11_03"); //May this armor protect you, as the Sleeper protects the Brotherhood!
  138: 
  139:     B_LogEntry          (GE_BecomeTemplar,"Gor Na Toth gave me my first templars' armor. Now I'm a proper member of the warrior clan!");
  140  
  141      Log_CreateTopic     (GE_TraderPSI,      LOG_NOTE);

C:\Users\amprosius\projects\gothic-1-community-patch\scriptbase\_work\Data\Scripts\Content\Story\Missions\DIA_VLK_572_Gravo.d:
   80      AI_Output (self, other,"DIA_Gravo_HelpHow_04_03"); //As a greenhorn, you depend on him. So you come to see me. I know a lot of people here Thorus listens to.
   81      AI_Output (self, other,"DIA_Gravo_HelpHow_04_04"); //They put in a good word for you, and Thorus is your friend again. Of course the boys want to see some ore for these kind of favors. Your ore.
   82:     AI_Output (self, other,"DIA_Gravo_HelpHow_04_05"); //And I take care that your ore gets to the right people...
   83: 
   84:     B_LogEntry(GE_TraderOC,"The digger Gravo is selling a special kind of service. If I get in trouble with important people in the Camp, I can pay him to settle it.");
   85  };
   86  

C:\Users\amprosius\projects\gothic-1-community-patch\scriptbase\_work\Data\Scripts\Content\Story\Missions\DIA_VLK_573_Graham.d:
   45  {
   46      AI_Output (other, self,"DIA_Graham_Hello_15_00"); //Hi! I'm new here.
   47:     AI_Output (self, other,"DIA_Graham_Hello_02_01"); //I'm Graham. I draw maps. I haven't seen you here before... What do you want?
   48: 
   49:     B_LogEntry( GE_TraderOC,"The digger Graham sells maps left of the main gate.");
   50  };
```

**Comment by szapp** [comment]
I will streamline this fix, once we have verified that it works as expected.

Although the test is fully automatic, some additional manual test will be necessary:
A.
1. Start the game without the fix
2. Talk to Gravo (before the topic was ever created)
3. Confirm that the log topic and log entry were not created 
4. Save and quit the game and start it with the fix
5. Confirm that the log topic *and* the entry exist now

B.
1. Start the game without the fix 
2. Talk to someone else before talking to Gravo and make sure the log topic exists before
3. Confirm that both log topic and log entry exist
4. Save and quit the game and start it with the fix
5. Confirm that the log entry concerning Gravo is the *first* entry of that topic<sup>[1]</sup>
6. Save and quit the game and start it again without the fix
7. Confirm that Gravo's log entry is not there anymore

[1] Gravo's log entry should not be added to the bottom of the topic. Otherwise it will always look like it's the newest entry. Therefore it is always added as the very first entry.

**Comment by AmProsius** [comment]
[ ] C:
1. Start the game without the fix.
2. Talk to someone that creates a log entry in that topic.
3. Talk to Gravo.
4. Confirm that both log topic and both log entries exist.
5. Save and quit the game and start it with the fix.
6. Confirm that the log entry concerning Gravo is untouched (should be the last entry of that topic).
7. Save and quit the game and start it again without the fix.
8. Confirm that Gravo's log entry is still there.

**Comment by szapp** [comment]
I tried to make porting this fix to other occurrences as easy as possible, by defining any specifics as constants at the beginning of the functions. These are preceded by the comment `// Parameters of this fix`. Still, the code will have to be carefully copied as there are multiple things to change:
- Function names
- Constants (as mentioned above)
- Fix ID, i.e. in the context `G1CP_IsFixApplied(37)`
- Function calls to the fix functions inside the test function

**Review by AmProsius — COMMENTED** [review]
Everything looks fine.

**Pull request merged**
